changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: 💥 Changements majeurs
      labels:
        - breaking-change
    - title: ✨ Nouvelles fonctionnalités
      labels:
        - enhancement
    - title: ⬆️ Dépendances
      labels:
        - dependencies
    - title: 🐛 Corrections de bugs
      labels:
        - bug
    - title: ♻️ Refactoring
      labels:
        - refactoring
    - title: 📝 Documentation
      labels:
        - documentation
    - title: ♿️ Accessibilité
      labels:
        - a11y
    - title: 🔧 Configuration
      labels:
        - configuration
