language: node_js
node_js: '12'

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn --frozen-lockfile --non-interactive
  - lerna bootstrap --ci

jobs:
  include:
    - stage: test
      name: 'Lint and test'
      before_script:
        - yarn global add codecov
      script:
        - lerna run lint
        - lerna run test
      after_script:
        - codecov
