version: 2.1

jobs:
  dummy:
    docker:
      - image: cimg/node:16.20-browsers
    steps:
      - run: echo "Hello World"

workflows:
  build-deploy:
    jobs:
      - dummy:
          filters:
            branches:
              only: v2
