version: 2.1
orbs:
  node: circleci/node@4.1.0

defaults: &defaults
  working_directory: ~/project/design-system
  docker:
    - image: circleci/node:12

aliases:
  - &restore-cache
    name: Restore Yarn Package Cache
    key: yarn-packages-{{ checksum "yarn.lock" }}

  - &save-cache
    name: Save Yarn Package Cache
    key: yarn-packages-{{ checksum "yarn.lock" }}
    paths:
      - node_modules/
      - ~/.cache
  - &run
    name: Install Dependencies
    command: yarn install --frozen-lockfile --non-interactive

workflow_filters: &filters
  filters:
    branches:
      ignore:
        - docs

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: *run
      - save_cache: *save-cache
  lint:
    <<: *defaults
    steps:
      - run: yarn lint
  test:
    <<: *defaults
    steps:
      - run: yarn test
  build:
    <<: *defaults
    steps:
      - run: yarn build

workflows:
  lint_test_build:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
      - build:
          <<: *filters
          requires:
            - install
