/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BackBtn: typeof import('./src/elements/BackBtn/BackBtn.vue')['default']
    BackToTopBtn: typeof import('./src/elements/BackToTopBtn/BackToTopBtn.vue')['default']
    ChipList: typeof import('./src/elements/ChipList/ChipList.vue')['default']
    ContextualMenu: typeof import('./src/patterns/ContextualMenu/ContextualMenu.vue')['default']
    CookieBanner: typeof import('./src/patterns/CookieBanner/CookieBanner.vue')['default']
    CookiesInformation: typeof import('./src/templates/CookiesPage/CookiesInformation/CookiesInformation.vue')['default']
    CookiesPage: typeof import('./src/templates/CookiesPage/CookiesPage.vue')['default']
    CookiesTable: typeof import('./src/templates/CookiesPage/CookiesTable/CookiesTable.vue')['default']
    CopyBtn: typeof import('./src/elements/CopyBtn/CopyBtn.vue')['default']
    DataList: typeof import('./src/elements/DataList/DataList.vue')['default']
    DataListItem: typeof import('./src/elements/DataList/DataListItem/DataListItem.vue')['default']
    DataListLoading: typeof import('./src/elements/DataList/DataListLoading/DataListLoading.vue')['default']
    ErrorPage: typeof import('./src/templates/ErrorPage/ErrorPage.vue')['default']
    FooterBtn: typeof import('./src/patterns/FooterWrapper/FooterBtn/FooterBtn.vue')['default']
    FooterWrapper: typeof import('./src/patterns/FooterWrapper/FooterWrapper.vue')['default']
    FranceConnectBtn: typeof import('./src/elements/FranceConnectBtn/FranceConnectBtn.vue')['default']
    HeaderLoading: typeof import('./src/elements/HeaderLoading/HeaderLoading.vue')['default']
    HelloWorld: typeof import('./src/elements/HelloWorld/HelloWorld.vue')['default']
    PageContainer: typeof import('./src/elements/PageContainer/PageContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkipLink: typeof import('./src/elements/SkipLink/SkipLink.vue')['default']
  }
}
