name: CI

on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: pnpm install

      - name: Run unit tests
        run:
          cd packages/synapse-bridge
          pnpm test:unit
